version: '3.1'
services: 
  db:
    image:  mysql
    container_name: devdojo
    environment:
      MYSQL_ROOT_PASSWORD: joao
    ports: 
    - "3306:3306"
    volumes:
    - devdojo:/var/lib/mysql

volumes:
  devdojo: