server:
  port: 81
  error:
    include-stacktrace: on_param

#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/anime?useSSL=false
#    username: root
#    password: joao
#  jpa:
#    hibernate:
#      ddl-auto: update

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

  